server:
  tomcat:
    threads:
      max: 500

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/bpmnexample
    #username: postgres
    #password: postgres
    hikari:
#      schema: example
      maximum-pool-size: 10

camunda:
  bpm:
    default-serialization-format: application/json
#    database:
#      table-prefix: EXAMPLE_
    history-level: none
    job-execution:
      enabled: true
      core-pool-size: 3
      max-pool-size: 10
      queue-capacity: 3
      wait-increase-factor: 1
      max-wait: 1100
      wait-time-in-millis: 1000
      lock-time-in-millis: 600000

example:
  analyst-url: http://127.0.0.1:8098/analyst
  tester-url: http://127.0.0.1:8099/tester
  developer1:
    host: 127.0.0.1
    port: 8087
  developer2:
    host: 127.0.0.1
    port: 8089
  review:
    host: 127.0.0.1
    port: 8091
